export const SET_ALERT = "SET_ALERT";
export const SET_LOADING = "SET_LOADING";
export const REMOVE_ALERT = "REMOVE_ALERT";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const USER_LOADED = "USER_LOADED";
export const AUTH_ERROR = "AUTH_ERROR";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const GET_PROFILE = "GET_PROFILE";
export const GET_PROFILES = "GET_PROFILES";
export const GET_REPOS = "GET_REPOS";
export const PROFILE_ERROR = "PROFILE_ERROR";
export const CLEAR_PROFILE = "CLEAR_PROFILE";
export const UPDATE_PROFILE = "UPDATE_PROFILE";
export const ACCOUNT_DELETED = "ACCOUNT_DELETED";
export const GET_POSTS = "GET_POSTS";
export const GET_POST = "GET_POST";
export const POST_ERROR = "POST_ERROR";
export const UPDATE_LIKES = "UPDATE_LIKES";
export const DELETE_POST = "DELETE_POST";
export const ADD_POST = "ADD_POST";
export const ADD_COMMENT = "ADD_COMMENT";
export const REMOVE_COMMENT = "REMOVE_COMMENT";
export const ADD_JOB  ="ADD_JOB";
export const GET_JOB ="GET_JOB";
export const GET_JOBS ="GET_JOBS";
export const JOB_ERROR ="JOB_ERROR";
export const DELETE_JOB="DELETE_JOB";
export const SENT_STK =" SENT_SUCCESS ";
export const SENT_FAIL= "SENT_FAIL";
export const PAYPAL_SENT="PAYPAL_SENT";
export const PAYPAL_FAIL="PAYPAL_PAYPAL";
export const FORGET_PASSWORD_SUCCESS="FORGET_PASSWORD_SUCCESS";
export const FORGET_PASSWORD_FAIL="FORGET_PASSWORD_FAIL";
export const RESET_PASSWORD_SUCCESS="RESET_PASSWORD_SUCCESS";
export const RESET_PASSWORD_FAIL="RESET_PASSWORD_FAIL"
export const GET_MEETINGS ="GET_MEETINGS "
export const ADD_MEETING ="ADD_MEETING"
export const MEETING_ERROR ="MEETING_ERROR"
export const FILTER_PROFILE="FILTER_PROFILE"
export const   CLEAR_FILTER ="  CLEAR_FILTER"
